object FrmStartTab: TFrmStartTab
  Left = 0
  Top = 0
  Caption = 'Start New Tab'
  ClientHeight = 729
  ClientWidth = 1217
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  Position = poMainFormCenter
  OnCreate = FormCreate
  TextHeight = 13
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 1217
    Height = 41
    Align = alTop
    TabOrder = 0
    object Label1: TLabel
      Left = 533
      Top = 9
      Width = 91
      Height = 23
      Caption = 'Open Tabs'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -19
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object EdtSearch: TEdit
      AlignWithMargins = True
      Left = 4
      Top = 4
      Width = 477
      Height = 33
      Align = alLeft
      CharCase = ecUpperCase
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -21
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
      TabOrder = 0
      TextHint = 'Search'
      OnChange = EdtSearchChange
    end
  end
  object Panel3: TPanel
    Left = 0
    Top = 41
    Width = 1217
    Height = 426
    Align = alClient
    TabOrder = 1
    object DBCtrlGrid1: TDBCtrlGrid
      Left = 1
      Top = 1
      Width = 480
      Height = 424
      Align = alLeft
      DataSource = DMMidas.DSClientes
      PanelHeight = 70
      PanelWidth = 463
      TabOrder = 0
      RowCount = 6
      SelectedColor = clMoneyGreen
      object DBText1: TDBText
        Left = 12
        Top = 11
        Width = 405
        Height = 17
        DataField = 'NombreCompleto2'
        DataSource = DMMidas.DSClientes
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object DBText2: TDBText
        Left = 296
        Top = 19
        Width = 121
        Height = 17
        Alignment = taRightJustify
        DataField = 'CELULAR'
        DataSource = DMMidas.DSClientes
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
    end
    object Panel2: TPanel
      Left = 1049
      Top = 1
      Width = 167
      Height = 424
      Align = alRight
      TabOrder = 1
      object btnCancel: TButton
        AlignWithMargins = True
        Left = 4
        Top = 4
        Width = 159
        Height = 55
        Align = alTop
        Caption = 'Cancel'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ModalResult = 2
        ParentFont = False
        TabOrder = 0
      end
      object btnOK: TButton
        AlignWithMargins = True
        Left = 4
        Top = 126
        Width = 159
        Height = 55
        Align = alTop
        Caption = 'Select Customer'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ModalResult = 1
        ParentFont = False
        TabOrder = 1
      end
      object btnStartNewTab: TButton
        AlignWithMargins = True
        Left = 4
        Top = 65
        Width = 159
        Height = 55
        Align = alTop
        Caption = 'Start New Tab'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ModalResult = 8
        ParentFont = False
        TabOrder = 2
        Visible = False
      end
      object BtnAddTable: TButton
        AlignWithMargins = True
        Left = 4
        Top = 187
        Width = 159
        Height = 55
        Align = alTop
        Caption = 'Add TAB to Table'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = []
        ModalResult = 6
        ParentFont = False
        TabOrder = 3
        Visible = False
      end
    end
    object DBCtrlGrid2: TDBCtrlGrid
      Left = 513
      Top = 1
      Width = 536
      Height = 424
      Align = alClient
      DataSource = DMMidas.dsOpenTabs
      PanelHeight = 70
      PanelWidth = 519
      TabOrder = 2
      RowCount = 6
      SelectedColor = clCream
      Touch.InteractiveGestures = [igZoom, igPan, igRotate, igTwoFingerTap, igPressAndTap]
      Touch.InteractiveGestureOptions = [igoPanSingleFingerHorizontal, igoPanSingleFingerVertical, igoParentPassthrough]
      object DBText3: TDBText
        Left = 20
        Top = 8
        Width = 317
        Height = 25
        DataField = 'CUSTOMER'
        DataSource = DMMidas.dsOpenTabs
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -19
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object DBText4: TDBText
        Left = 396
        Top = 6
        Width = 85
        Height = 17
        Alignment = taRightJustify
        DataField = 'BALANCE'
        DataSource = DMMidas.dsOpenTabs
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object DBText5: TDBText
        Left = 20
        Top = 52
        Width = 317
        Height = 16
        DataField = 'DATE'
        DataSource = DMMidas.dsOpenTabs
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object DBText6: TDBText
        Left = 664
        Top = 6
        Width = 177
        Height = 22
        Alignment = taRightJustify
        DataField = 'SERVER_DEFINE'
        DataSource = DMMidas.dsOpenTabs
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object DBText7: TDBText
        Left = 524
        Top = 6
        Width = 85
        Height = 17
        Alignment = taRightJustify
        DataField = 'GROUP_BALANCE'
        DataSource = DMMidas.dsOpenTabs
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -16
        Font.Name = 'Tahoma'
        Font.Style = [fsBold]
        ParentFont = False
      end
      object DBText8: TDBText
        Left = 20
        Top = 34
        Width = 317
        Height = 14
        DataField = 'TRANSACTIONNUMBER_DEFINE'
        DataSource = DMMidas.dsOpenTabs
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object DBText9: TDBText
        Left = 664
        Top = 20
        Width = 177
        Height = 16
        Alignment = taRightJustify
        DataField = 'BUTTON_CAPTION'
        DataSource = DMMidas.dsOpenTabs
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
      object DBText10: TDBText
        Left = 664
        Top = 35
        Width = 177
        Height = 14
        Alignment = taRightJustify
        DataField = 'TELEPHONE'
        DataSource = DMMidas.dsOpenTabs
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Tahoma'
        Font.Style = []
        ParentFont = False
      end
    end
    object Panel4: TPanel
      Left = 481
      Top = 1
      Width = 32
      Height = 424
      Align = alLeft
      TabOrder = 3
    end
  end
  object TouchKeyboard1: TTouchKeyboard
    AlignWithMargins = True
    Left = 10
    Top = 477
    Width = 1197
    Height = 242
    Margins.Left = 10
    Margins.Top = 10
    Margins.Right = 10
    Margins.Bottom = 10
    Align = alBottom
    GradientEnd = clSilver
    GradientStart = clGray
    Layout = 'Standard'
  end
end
