object FrmShowMessage: TFrmShowMessage
  Left = 0
  Top = 0
  BorderIcons = []
  Caption = 'Message'
  ClientHeight = 129
  ClientWidth = 465
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  PopupMode = pmAuto
  Position = poMainFormCenter
  OnClose = FormClose
  PixelsPerInch = 96
  TextHeight = 13
  object Memo1: TMemo
    Left = 0
    Top = 0
    Width = 465
    Height = 96
    TabStop = False
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -16
    Font.Name = 'Verdana'
    Font.Style = [fsBold]
    ParentFont = False
    ReadOnly = True
    TabOrder = 1
    ExplicitHeight = 80
  end
  object v: TPanel
    Left = 0
    Top = 96
    Width = 465
    Height = 33
    Align = alBottom
    TabOrder = 0
    ExplicitTop = 80
    object BitBtnOk: TButton
      AlignWithMargins = True
      Left = 386
      Top = 4
      Width = 75
      Height = 25
      Align = alRight
      Caption = '&Ok'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Verdana'
      Font.Style = []
      ModalResult = 1
      ParentFont = False
      TabOrder = 0
    end
  end
  object Timer1: TTimer
    Interval = 7000
    OnTimer = Timer1Timer
    Left = 184
  end
end
